version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: 'android-10.0'
      VERSION: '3.0.0-test'
      MAINTAINER: 'PBRP Team'
      VENDOR: 'xiaomi'
      CODENAME: 'joyeuse'
      BUILD_LUNCH: 'omni_phoenix-eng'
      FLAVOR: "eng"
      TEST_BUILD: 'true'
      #EXTRA_CMD: "rm -rf build/soong && git clone https://github.com/PitchBlackRecoveryProject/android_build_soong -b android-10-fixes build/soong && rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 vendor/pb"
      CHANGELOG: |
         Initial Test Build
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "ALL IN REMOTE"
          command: |
            curl -sL https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/Tess/remote_build.sh -o build.sh
            source build.sh
workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-10.0'
          context: org-global
