name: Test Build
on:
  push:
  workflow_dispatch:

env:
  MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
  DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp -b test-a10"
  VENDOR: "xiaomi"
  CODENAME: "phoenix"
  TARGET: "recoveryimage"
  FLAVOR: "eng"
  TZ: "Asia/Kolkata"
  BUILD_RELEASE_TYPE: "TEST"
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Mock Build
        run: |
          # Mock Official Build
          mkdir -p work/out/target/product/phoenix
          cd work/out/target/product/phoenix
          wget https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp/releases/download/null/PBRP-phoenix-3.0.0-20210222-1745-UNOFFICIAL.zip
          wget https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp/releases/download/null/recovery.img

      - name: Setup Deps
        run: |
          sudo apt-get install sshpass -y
          curl -s https://api.github.com/repos/tcnksm/ghr/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux_amd64")) | .browser_download_url' | wget -qi -
          tar -xzf ghr_*_amd64.tar.gz --wildcards 'ghr*/ghr' --strip-components 1
          sudo mv ./ghr /usr/local/bin/ && rm -rf ghr_*_amd64.tar.gz

      - name: PB deploy
        run: |
          cd work
          git clone https://github.com/PitchBlackRecoveryProject/vendor_utils vendor/utils
          git clone https://github.com/PitchBlackRecoveryProject/android_bootable_recovery bootable/recovery
          bash vendor/utils/pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}
